[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.20.1

[env:nodemcuv2-ota]
extends = env:nodemcuv2
upload_protocol = espota
upload_port = soil-moisture.local
upload_flags = --auth=${sysenv.OTA_PASSWORD}
